name = "VoxelwiseConstantMapping"
uuid = "30c4ba4d-5c6d-4df8-9a6f-7ded98721337"
authors = ["Wonseok Shin <wsshin97@gmail.com>"]
version = "0.1.0"

[deps]
AbbreviatedTypes = "1766def0-c946-4dda-a59e-d0d07f8410f7"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
AbbreviatedTypes = "^0.1.3"
StaticArrays = "^1.0.0"
julia = "^1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
