name = "VoxelwiseConstantMapping"
uuid = "30c4ba4d-5c6d-4df8-9a6f-7ded98721337"
authors = ["Wonseok Shin <wsshin97@gmail.com>"]
version = "0.1.0"

[deps]
AbbreviatedTypes = "1766def0-c946-4dda-a59e-d0d07f8410f7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
AbbreviatedTypes = "^0.2.1"
julia = "^1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
