name = "VoxelwiseConstantMapping"
uuid = "30c4ba4d-5c6d-4df8-9a6f-7ded98721337"
authors = ["Wonseok Shin <wsshin97@gmail.com>"]
version = "0.1.0"

[deps]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "^1"
